name: Check

on:
  workflow_call:

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetEnvironment: [ dev, ppr, prd ]
    steps:
      - uses: actions/checkout@master
      - name: Lint
        uses: hiberbee/github-action-helm@latest
        with:
          helm: lint  --values ./values-${{matrix.targetEnvironment}}.yaml


